AWSTemplateFormatVersion: 2010-09-09
Description: "CloudFormation template to create base RDS Postgres stack"
Parameters:
  ParentVPCStack:
    Description: "Stack name of parent VPC stack."
    Type: String

  EnvironmentName:
    Description: An environment name that is postfixed to resource names
    Type: String

  DBInstanceName:
    Description: RDS Instance Name
    Type: String

  DBName:
    Type: String
    NoEcho: true
    Description: "Secret Database Name"

  DBMasterUsername:
    Description: "The master user name for the DB instance (ignored when DBSnapshotIdentifier is set, value used from snapshot)."
    Type: String
    NoEcho: true
    Default: postgres

  DBMasterUserPassword:
    Type: String
    NoEcho: true
    Description: "Secret Database Password"

  DBMultiAZ:
    Description: "Specifies if the database instance is deployed to multiple Availability Zones for HA."
    Type: String
    Default: false
    AllowedValues: [true, false]

  DBEngineVersion:
    Description: "PostgreSQL version."
    Type: String
    Default: "17.2"

  DBInstanceClass:
    Description: "The instance type of database server."
    Type: String
    Default: "db.t3.micro"

  DBAllocatedStorage:
    Description: "The allocated storage size, specified in GB (ignored when DBSnapshotIdentifier is set, value used from snapshot)."
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 16384

  DBBackupRetentionPeriod:
    Description: "The number of days to keep snapshots of the database."
    Type: Number
    MinValue: 0
    MaxValue: 35
    Default: 30

  PreferredBackupWindow:
    Description: "The daily time range in UTC during which you want to create automated backups."
    Type: String
    Default: "09:54-10:24"

  PreferredMaintenanceWindow:
    Description: The weekly time range (in UTC) during which system maintenance can occur.
    Type: String
    Default: "tue:07:00-tue:07:30"

Resources:
  DBDefaultSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "difatto-db-default-sg-${EnvironmentName}"
      GroupDescription: Handles Public access to RDS from the Internet
      VpcId: { "Fn::ImportValue": !Sub "${ParentVPCStack}-VPC" }
      SecurityGroupIngress:
        - Description: Allows traffic in from the internet
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "[rds <- *] - difatto-${EnvironmentName}-sg"

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Sub "difatto-subnetgrp-${EnvironmentName}"
      DBSubnetGroupDescription: !Ref "AWS::StackName"
      SubnetIds:
        !Split [",", { "Fn::ImportValue": !Sub "${ParentVPCStack}-DBSubnets" }]

  DBInstance:
    DeletionPolicy: Snapshot # default
    UpdateReplacePolicy: Snapshot
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceName
      AllocatedStorage: !Ref DBAllocatedStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      EnableIAMDatabaseAuthentication: false
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      MultiAZ: !Ref DBMultiAZ
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      StorageType: gp2
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref DBDefaultSecurityGroup

Outputs:
  DBInstanceArn:
    Description: Database Instance Arn
    Value: !GetAtt DBInstance.DBInstanceArn
    Export:
      Name: !Sub "${AWS::StackName}-DBInstanceArn"
  DBEndpoint:
    Description: Database Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
