name: Difatto Cloudformation DELETE
on:
  workflow_dispatch:
    inputs:
      environment:
        description: CF Stack to delete
        type: environment
env:
  REPO_ORG: "iofreddy85"
  DEV_OPS_REPO_ID: ${{ vars.DEV_OPS_REPO_ID }}
  PAT: ${{ secrets.DIFATTO_DEVOPS_PAT }}

  ECR_IMAGES_REPOSITORY: ${{ vars.ECR_IMAGES_REPOSITORY }}
  DB_INSTANCE_NAME: ${{ vars.DB_INSTANCE_NAME }}
  VPC_STACK_NAME: ${{ vars.VPC_STACK_NAME }}
  DATABASE_STACK_NAME: ${{ vars.DATABASE_STACK_NAME }}
  SERVICES_STACK_NAME: ${{ vars.SERVICES_STACK_NAME }}
  PAYLOAD_RDS2ECS_SG: "ECSRDSSecurityGroup"

  # DNS_ZONE: ${{ vars.CLOUDFLARE_DNS_ZONE }}
  # Repository Secrets
  # CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
jobs:
  delete-stack:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Delete Stack
        working-directory: "./scripts"
        run: |
          source ./helpers.sh
          # source ./cloudflare_api.sh

          STACK_NAME=${{ inputs.environment }}

          img_length=$(aws ecr list-images --repository-name $ECR_IMAGES_REPOSITORY | jq  '.imageIds | length')
          if [[ $img_length -ne 0 ]]; then
            echo "Images to delete: $img_length..."
            imgs_array=($(aws ecr list-images --repository-name $ECR_IMAGES_REPOSITORY | jq  '.imageIds | map("imageTag="+.imageTag) | join(" ")' -r))
            aws ecr batch-delete-image --repository-name $ECR_IMAGES_REPOSITORY --image-ids "${imgs_array[@]}"
          else
            echo "No images to delete..."
          fi

          # remove sg from rds
          remove_sgs_rds_instance \
            $SERVICES_STACK_NAME \
            $DB_INSTANCE_NAME \
            $PAYLOAD_RDS2ECS_SG

          sleep 60

          # aws lambda update-function-configuration \
          #   --function-name ${{ vars.LAMBDA_DBDUMPS_FUNCTION }} \
          #   --file-system-configs=[] \
          #   --vpc-config SubnetIds=[],SecurityGroupIds=[]

          # aws cloudformation wait stack-delete-complete \
          #   --stack-name $LAMBDA_STACK_ID

          # Delete Services CF Stack
          echo "Deleting AWS Cloudformation Stack: $SERVICES_STACK_NAME"
          aws cloudformation delete-stack \
            --stack-name "$SERVICES_STACK_NAME"

          aws cloudformation wait stack-delete-complete \
            --stack-name "$SERVICES_STACK_NAME"

          # Delete RDS CF Stack
          echo "Deleting AWS Cloudformation Stack: $DATABASE_STACK_NAME"
          aws cloudformation delete-stack \
            --stack-name "$DATABASE_STACK_NAME"

          aws cloudformation wait stack-delete-complete \
            --stack-name "$DATABASE_STACK_NAME"

          # Delete VPC CF Stack
          echo "Deleting AWS Cloudformation Stack: $VPC_STACK_NAME"
          aws cloudformation delete-stack \
            --stack-name "$VPC_STACK_NAME"

          aws cloudformation wait stack-delete-complete \
            --stack-name "$VPC_STACK_NAME"

          echo "Deleting Github Environment: $STACK_NAME asyncronously"
          # Call workflow
          dispatch_delete_env_wf $STACK_NAME &

          # Delete DNSs created
          # cloudflare_delete_dns_record "${{ vars.QA_DNS_ADMIN_RECORD_ID }}"
          # cloudflare_delete_dns_record "${{ vars.STG_DNS_ADMIN_RECORD_ID }}"
          # cloudflare_delete_dns_record "${{ vars.QA_DNS_FE_RECORD_ID }}"
          # cloudflare_delete_dns_record "${{ vars.STG_DNS_FE_RECORD_ID }}"
